name: Build and Deploy
on: [push]
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Push
        run: |
          echo "${{ secrets.TOKEN_GITHUB }}" | docker login ghcr.io -u ahmaddwisetiawan --password-stdin
          docker build -t ghcr.io/ahmaddwisetiawan/$NAME_BARU:latest .
          docker push ghcr.io/ahmaddwisetiawan/$NAME_BARU:latest
  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Up
        run: |
          echo "services:
            webserver:
              image: ghcr.io/ahmaddwisetiawan/$NAME_BARU:latest
              ports:
                - '8080:80'" > docker-compose.yml
          docker compose up -d
