name: Build, Push and Deploy Docker Image

on: [push]

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: "ghcr.io/ahmaddwisetiawan/nginx-ahmaddwisetiawan"

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build Image
        run: docker build -t ${{ env.IMAGE_NAME }} .

      - name: Login to GitHub Registry
        run: echo "${{ secrets.TOKEN_GITHUB }}" | docker login ghcr.io -u ahmaddwisetiawan --password-stdin

      - name: Push Image
        run: docker push ${{ env.IMAGE_NAME }}

  deploy:
    needs: build-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to GitHub Registry
        run: echo "${{ secrets.TOKEN_GITHUB }}" | docker login ghcr.io -u ahmaddwisetiawan --password-stdin

      - name: stop and remove existing container
        run: docker compose down --rmi all || true

      - name: start container
        run: |
          docker compose up -d
          sleep 10

      - name: check container
        run: curl localhost:8080
